PRESETS = {'Config 1': {'machine': 'Shimadzu',
              'material': 'CNT-GFW',
              'general': {'sampling rate': '1000', 'filename': 'prueba_1.csv', 'max data': '500'},
              'machine_fields': {'repetitions': '500',
                                 'displacement readings': True,
                                 'displacement voltage': '1.0',
                                 'displacement distance': '10',
                                 'displacement distance units': 'mm',
                                 'load readings': True,
                                 'load force': '100',
                                 'load voltage': '1.0',
                                 'load force units': 'N'},
              'material_fields': {'test type': 'Cyclic (C)',
                                  'channels': '21',
                                  'debond': True,
                                  'length': '5',
                                  'width': '5',
                                  'height': '1',
                                  'sensor number': '1'},
              'board_fields': {'temp checkbox': True,
                               'temp units': 'C',
                               'rh checkbox': True,
                               'pressure checkbox': False,
                               'gas checkbox': False,
                               'light checkbox': True,
                               'lux units': 'ALS',
                               'lux bits': '16'}},
 'Config 2': {'machine': 'One-Axis Strain Prototype',
              'material': 'MWCNT',
              'general': {'sampling rate': '500', 'filename': 'prueba_2.csv', 'max data': '1000'},
              'machine_fields': {'repetitions': '300',
                                 'strain': '8',
                                 'hx711 load readings': True,
                                 'hx711 load cell capacity': '500',
                                 'hx711 load cell units': 'N',
                                 'motor displacement': '60'},
              'material_fields': {'channels': '8',
                                  'row': '2',
                                  'column': '3',
                                  'length': '10',
                                  'width': '3',
                                  'height': '0.5',
                                  'sensor number': '2'},
              'board_fields': {}},
 'nuevo': {'machine': 'One-Axis Strain Prototype',
           'material': 'MWCNT',
           'general': {'machine options': 'One-Axis Strain Prototype',
                       'material options': 'MWCNT',
                       'sampling rate': '500',
                       'filename': 'prueba_2.csv',
                       'max data': '1000'},
           'machine_fields': {'repetitions': '300',
                              'strain': '8',
                              'hx711 load readings': True,
                              'hx711 load cell capacity': '500',
                              'hx711 load cell units': 'N',
                              'motor displacement': '60'},
           'material_fields': {'channels': '8',
                               'row': '2',
                               'column': '3',
                               'length': '10',
                               'width': '3',
                               'height': '0.5',
                               'sensor number': '2'},
           'board_fields': {'temp checkbox': False,
                            'temp units': '',
                            'rh checkbox': False,
                            'pressure checkbox': False,
                            'pressure units': '',
                            'gas checkbox': False,
                            'gas units': '',
                            'light checkbox': True,
                            'lux units': '',
                            'lux bits': ''}},
 'nueva config': {'machine': '',
                  'material': '',
                  'general': {'machine options': 'Chooze a Machine',
                              'material options': 'Choose a Material',
                              'sampling rate': '',
                              'filename': '',
                              'max data': ''},
                  'machine_fields': {},
                  'material_fields': {},
                  'board_fields': {'temp checkbox': False,
                                   'temp units': '',
                                   'rh checkbox': False,
                                   'pressure checkbox': True,
                                   'pressure units': '',
                                   'gas checkbox': False,
                                   'gas units': '',
                                   'light checkbox': True,
                                   'lux units': 'ALS',
                                   'lux bits': ''}}}
